### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by arpecop** [MikeBild/graphql-pouch#43]
Cannot install, the installer trying to compile old version of sqlite which url does not exist

**Comment by MikeBild** [comment]
I'll try to fix that.

**Comment by joshglenn** [comment]
Yes, I'm having that issue as well. I'm looking into it to see if I can fix it. So far, no luck. I don't see sqlite in the package.json, so I don't even know where to find the package that needs to install a newer version.

**Comment by joshglenn** [comment]
I just created a pull request that resolves this issue... with one caveat. The same modifications to the package.json that are in this pull request also have to be made to any projects that depend on this one. Not ideal, but it works.

Add the following to package.json of any project that references this:

```
  "resolutions": {
    "nan": "2.14.1",
    "node-gyp": "5.1.0"
  },
```

... with some context:

```
{
  "name": "graphql-pouch-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "resolutions": {
    "nan": "2.14.1",
    "node-gyp": "5.1.0"
  },
  "dependencies": {
    "graphql-pouch": "<varies>"
  }
}
```

**Comment by joshglenn** [comment]
Here is an [example repo](https://github.com/joshglenn/graphql-pouch-test) I made to demonstrate.
