### ISSUE TITLE
Does not exist on NPM

### ISSUE THREAD

**Issue by a-s-o** [MikeBild/graphql-pouch#8]
Hello Mike,

Looks like the package is not on npm; is it ready for use? I am starting an electron app this week and would like to use this.

See 404 at https://www.npmjs.com/package/graphql-pouch

As a side note, I may be able to help with things a bit if you need it. This looks like an interesting package.

**Comment by MikeBild** [comment]
Hello,

your offer sounds very good. Yes, help would certainly needed. IMO Some more tests would be very helpful and that's a good starting point to fix issues. I'll probably work this weekend to publish the first version 1.0.0 to NPM. What do you think?

**Comment by a-s-o** [comment]
Sure, any particular area to focus on? I see you have some integration tests already which are a good start.

**Comment by MikeBild** [comment]
No preferences. Yes, more integration tests would nice. I thought upsert/delete mutations could include result issues. I'll open an issue.

**Comment by a-s-o** [comment]
Hi, may I ask why you are not developing this as a pouchdb plugin (https://pouchdb.com/api.html#plugins)? Was there some limitation to that approach?

It may be easier to allow user to create/configure the DB layer.

**Comment by MikeBild** [comment]
Hi,

I'm not quit sure which part you mean. Yes, I guess it's a good refactor option to create/configure and using the PouchDB layer. The current environment settings and DB access implementation is not very elegant. A refactoring, especially in case of "using as library", would be very useful and I would be glad to see a PR. BTW - What's your name? ;)

**Comment by a-s-o** [comment]
Hi, my name is Amandeep :)

I will make a pull request. I created a separate issue #10 so we can discuss the API before I do that.

**Comment by MikeBild** [comment]
OK. Publish to NPM is very close.

**Comment by a-s-o** [comment]
Great, thanks. No rush, hope you can enjoy the weekend too 👍

**Comment by MikeBild** [comment]
done - 80c8435446fbbe22f861d3d674aa06a8a13cf7f9
